const coffee = [
    {
        "id": 1,
        "name": "Black Coffee La Paz",
        "description": "cafe negro como tu ogt",
        "category": "Black",
        "origin": "Bolivia",
        "intensity": 0 - 10,
        // "type": "grain - capsule",
        "images": [
            {
                "id": 1,
                "url": "pijurro.png"
            },
            {

            }
        ]
        
    }
]

const user = [
    {
        "id": 1,
        "name": "",
        "username": "",
        "email": "",
        "password": "",
        "img": "",
        
    }
]

 

